version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: quarkus-app
    ports:
      - "8080:8080"
      - "5005:5005"  # Debug port
    env_file: .env
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2  # Maven cache
    depends_on:
      - keycloak
    networks:
      - quarkus-net

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: keycloak
    env_file: .env
    command:
      - start-dev
    ports:
      - "8180:8080"
    depends_on:
      - keycloak-db
    networks:
      - quarkus-net

  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    env_file: .env
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    networks:
      - quarkus-net

volumes:
  keycloak-data:

networks:
  quarkus-net:
    driver: bridge