{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "quarkus-base.fullname" . }}
  labels:
    {{- include "quarkus-base.labels" . | nindent 4 }}
spec:
  host: {{ .Values.route.host }}
  port:
    targetPort: http
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "quarkus-base.fullname" . }}
    weight: 100
{{- end }}