quarkus.smallrye-openapi.path=/openapi
# Enable/disable swagger UI
quarkus.swagger-ui.enable=true
# Customize the title and other info
quarkus.smallrye-openapi.info-title=PTSS SUPPORT API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=This is the ptss support api
quarkus.ratelimit.buckets.default.max-requests=100
quarkus.ratelimit.buckets.default.time-window=PT1M
quarkus.rate-limit.requests=100
quarkus.rate-limit.period=1m

# JWT Validation
mp.jwt.verify.publickey=your-public-key
mp.jwt.verify.issuer=your-keycloak-realm
quarkus.smallrye-jwt.enabled=true

# Identity Service Configuration
quarkus.rest-client."org.ptss.support.identityservice.clients.IdentityServiceClient".url=http://localhost:8080
identity-service/mp-rest/scope=javax.inject.Singleton


quarkus.http.port=8080
