name: 'Setup Java Environment'
description: 'Checks out repository, sets up JDK, and prepares Maven wrapper'

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Grant execute permission for mvnw
      run: chmod +x mvnw
      shell: bash