replicaCount: 2

image:
  pullPolicy: Always

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  
securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]