name: 🚀 Deploy to Development

on:
  push:
    branches: [ development ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag (optional)'
        required: false
        default: 'latest'

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    environment: development
    steps:
      - uses: actions/checkout@v3

      - name: Set Repository Name
        id: repo_name
        run: |
          echo "name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "artifact_name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]' | tr '/' '-')" >> $GITHUB_OUTPUT

      - name: Generate Version Tag
        id: generate_tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ "${{ github.event.inputs.tag }}" != "latest" ]; then
            echo "version=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          else
            echo "version=$(date +'%Y%m%d')-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          fi

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
          tar -xvf openshift-client-linux.tar.gz -C /usr/local/bin
          chmod +x /usr/local/bin/oc

      - name: Login to OpenShift
        run: |
          oc login --token=${{ secrets.OSC_TOKEN }} --server=${{ secrets.OSC_SERVER }}

      - name: Set Application Variables
        run: |
          HELM_RELEASE_NAME=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]' | tr '_' '-')
          echo "ROUTE_HOST=${HELM_RELEASE_NAME}-dev.${{ secrets.APPS_DOMAIN }}" >> $GITHUB_ENV
          echo "APP_NAME=${HELM_RELEASE_NAME}" >> $GITHUB_ENV

      - name: Build and Deploy with Quarkus OpenShift
        run: |
          chmod +x mvnw
          ./mvnw clean package \
            -Dquarkus.container-image.registry=ghcr.io \
            -Dquarkus.container-image.group=${{ github.repository }} \
            -Dquarkus.container-image.name=${{ env.APP_NAME }} \
            -Dquarkus.container-image.tag=${{ steps.generate_tag.outputs.version }} \
            -Dquarkus.openshift.route.host=${{ env.ROUTE_HOST }} \
            -Dquarkus.openshift.deployment.namespace=${{ secrets.OSC_DEV_PROJECT }} \
            -Dquarkus.kubernetes-client.master-url=${{ secrets.OSC_SERVER }} \
            -Dquarkus.kubernetes-client.token=${{ secrets.OSC_TOKEN }} \
            -Dquarkus.openshift.env.configmaps=${{ env.APP_NAME }}-config \
            -Dquarkus.profile=dev

      - name: Deploy to OpenShift
        run: |
          ./mvnw quarkus:deploy \
            -Dquarkus.profile=dev \
            -Dquarkus.kubernetes-client.master-url=${{ secrets.OSC_SERVER }} \
            -Dquarkus.kubernetes-client.token=${{ secrets.OSC_TOKEN }}

      - name: Wait for Deployment
        run: |
          oc rollout status deployment/${APP_NAME} -n ${{ secrets.OSC_DEV_PROJECT }} --timeout=180s

      - name: Run E2E Tests
        run: |
          echo "TODO: Add E2E tests using your preferred testing framework"
          echo "These tests should run against the newly deployed dev environment"

      - name: Performance Tests (Basic)
        run: |
          echo "TODO: Add basic k6 performance tests against dev environment"
          echo "More extensive performance testing will be done in production deployment"