name: 🚀 Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger
    inputs:
      tag:
        description: 'Image tag to deploy'
        required: true

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Set Repository Name
        id: repo_name
        run: |
          echo "name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: SonarQube Scan and Quality Gate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          ./mvnw sonar:sonar \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
          
          # Quality Gate Check
          SONAR_CE_TASK_URL=$(curl -s \
          -u "${{ secrets.SONAR_TOKEN }}:" \
          "${{ secrets.SONAR_HOST_URL }}/api/ce/task?componentKey=${{ secrets.SONAR_PROJECT_KEY }}")
          
          TASK_ID=$(echo $SONAR_CE_TASK_URL | jq -r '.task.id')
          
          # Wait for task to complete and get analysis ID
          ANALYSIS_ID=$(curl -s \
          -u "${{ secrets.SONAR_TOKEN }}:" \
          "${{ secrets.SONAR_HOST_URL }}/api/ce/task?id=$TASK_ID" | \
          jq -r '.task.analysisId')
          
          # Check quality gate status
          QUALITY_GATE_STATUS=$(curl -s \
          -u "${{ secrets.SONAR_TOKEN }}:" \
          "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?analysisId=$ANALYSIS_ID" | \
          jq -r '.projectStatus.status')
          
          echo "Quality Gate Status: $QUALITY_GATE_STATUS"
          
          if [ "$QUALITY_GATE_STATUS" != "OK" ]; then
            echo "❌ Quality Gate Failed"
            exit 1
          fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get Image Tag
        id: get_tag
        run: |
          TAG=${{ github.event.inputs.tag }}
          if [ "${{ github.event_name }}" = "push" ]; then
            TAG=$(date +'%Y%m%d')-${GITHUB_SHA::7}
          fi
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Verify Image Exists
        run: |
          IMAGE="ghcr.io/${{ steps.repo_name.outputs.name }}:${{ steps.get_tag.outputs.tag }}"
          
          echo "🔍 Verifying image: $IMAGE"
          
          # Try to inspect the image
          if ! docker pull $IMAGE >/dev/null 2>&1; then
            echo "❌ Error: Image $IMAGE not found in registry"
            echo "Please ensure the image was built and pushed successfully in the development pipeline"
            exit 1
          fi
          
          echo "✅ Image verification successful"
      
      - name: Install OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
          tar -xvf openshift-client-linux.tar.gz -C /usr/local/bin
          chmod +x /usr/local/bin/oc
        
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0
        
      - name: Login to OpenShift
        run: |
          oc login --token=${{ secrets.OSC_TOKEN }} --server=${{ secrets.OSC_SERVER }}

      - name: Set App Name
        id: app_name
        run: |
          echo "name=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]' | tr '_' '-')" >> $GITHUB_OUTPUT
  
      - name: Clone Platform Config
        uses: actions/checkout@v3
        with:
          repository: PTSS-Support/platform-config
          path: platform-config
          token: ${{ secrets.PLATFORM_CONFIG_PAT }}

      - name: Apply Platform Configs
        run: |
          NAMESPACE=${{ secrets.OSC_PROD_PROJECT }}

          # Apply common configs if they exist and are not empty
          if [ -d "platform-config/common/configmaps" ] && [ "$(ls -A platform-config/common/configmaps)" ]; then
            oc apply -f platform-config/common/configmaps/ -n ${NAMESPACE}
          fi
          if [ -d "platform-config/common/secrets" ] && [ "$(ls -A platform-config/common/secrets)" ]; then
            oc apply -f platform-config/common/secrets/ -n ${NAMESPACE}
          fi

          # Apply app-specific configs if they exist and are not empty
          if [ -d "platform-config/apps/${{ steps.app_name.outputs.name }}/configmaps" ] && [ "$(ls -A platform-config/apps/${{ steps.app_name.outputs.name }}/configmaps)" ]; then
            oc apply -f platform-config/apps/${{ steps.app_name.outputs.name }}/configmaps/ -n ${NAMESPACE}
          fi
          if [ -d "platform-config/apps/${{ steps.app_name.outputs.name }}/secrets" ] && [ "$(ls -A platform-config/apps/${{ steps.app_name.outputs.name }}/secrets)" ]; then
            oc apply -f platform-config/apps/${{ steps.app_name.outputs.name }}/secrets/ -n ${NAMESPACE}
          fi

          # Apply environment-specific common configs
          if [ -d "platform-config/environments/prod/common/configmaps" ] && [ "$(ls -A platform-config/environments/prod/common/configmaps)" ]; then
            oc apply -f platform-config/environments/prod/common/configmaps/ -n ${NAMESPACE}
          fi
          if [ -d "platform-config/environments/prod/common/secrets" ] && [ "$(ls -A platform-config/environments/prod/common/secrets)" ]; then
            oc apply -f platform-config/environments/prod/common/secrets/ -n ${NAMESPACE}
          fi

          # Apply environment-specific app configs
          if [ -d "platform-config/environments/prod/apps/${{ steps.app_name.outputs.name }}/configmaps" ] && [ "$(ls -A platform-config/environments/prod/apps/${{ steps.app_name.outputs.name }}/configmaps)" ]; then
            oc apply -f platform-config/environments/prod/apps/${{ steps.app_name.outputs.name }}/configmaps/ -n ${NAMESPACE}
          fi
          if [ -d "platform-config/environments/prod/apps/${{ steps.app_name.outputs.name }}/secrets" ] && [ "$(ls -A platform-config/environments/prod/apps/${{ steps.app_name.outputs.name }}/secrets)" ]; then
            oc apply -f platform-config/environments/prod/apps/${{ steps.app_name.outputs.name }}/secrets/ -n ${NAMESPACE}
          fi
      
      - name: Deploy to OpenShift Prod
        run: |
          ROUTE_HOST="${{ steps.app_name.outputs.name }}.${{ secrets.APPS_DOMAIN }}"
          
          helm upgrade --install ${{ steps.app_name.outputs.name }} ./helm \
            --namespace ${{ secrets.OSC_PROD_PROJECT }} \
            --values ./helm/values.yaml \
            --values ./helm/values-prod.yaml \
            --set image.registry=ghcr.io \
            --set image.repository=${{ steps.repo_name.outputs.name }} \
            --set image.tag=${{ steps.get_tag.outputs.tag }} \
            --set route.host=${ROUTE_HOST}
            
      - name: Wait for Deployment
        run: |
          oc rollout status deployment/${{ steps.app_name.outputs.name }} -n ${{ secrets.OSC_PROD_PROJECT }} --timeout=150s

      - name: Verify Deployment
        run: |
          # Check if all pods are ready
          READY_PODS=$(oc get deployment ${{ steps.app_name.outputs.name }} -n ${{ secrets.OSC_PROD_PROJECT }} -o jsonpath='{.status.readyReplicas}')
          DESIRED_PODS=$(oc get deployment ${{ steps.app_name.outputs.name }} -n ${{ secrets.OSC_PROD_PROJECT }} -o jsonpath='{.spec.replicas}')
          
          if [ "$READY_PODS" != "$DESIRED_PODS" ]; then
            echo "❌ Deployment verification failed: $READY_PODS/$DESIRED_PODS pods ready"
            exit 1
          fi

          echo "✅ Deployment verification successful: $READY_PODS/$DESIRED_PODS pods ready"
