name: 🚀 Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Manual trigger
    inputs:
      tag:
        description: 'Image tag to deploy'
        required: true

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: Set Repository Name
        id: repo_name
        run: |
          echo "name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

          - name: Login to GitHub Container Registry
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Get Image Tag
        id: get_tag
        run: |
          TAG=${{ github.event.inputs.tag }}
          if [ "${{ github.event_name }}" = "push" ]; then
            TAG=$(date +'%Y%m%d')-${GITHUB_SHA::7}
          fi
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
  
      - name: Verify Image Exists
        run: |
          IMAGE="ghcr.io/${{ steps.repo_name.outputs.name }}:${{ steps.get_tag.outputs.tag }}"
          
          echo "🔍 Verifying image: $IMAGE"
          
          # Try to inspect the image
          if ! docker pull $IMAGE >/dev/null 2>&1; then
            echo "❌ Error: Image $IMAGE not found in registry"
            echo "Please ensure the image was built and pushed successfully in the development pipeline"
            exit 1
          fi
          
          echo "✅ Image verification successful"
      
      - name: Install OpenShift CLI
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
          tar -xvf openshift-client-linux.tar.gz -C /usr/local/bin
          chmod +x /usr/local/bin/oc
      
      - name: Deploy to OpenShift Prod
        run: |
          oc login --token=${{ secrets.OSC_TOKEN }} --server=${{ secrets.OSC_SERVER }}
          oc project ${{ secrets.OSC_PROD_PROJECT }}
          
          # Get image tag
          TAG=${{ github.event.inputs.tag }}
          if [ "${{ github.event_name }}" = "push" ]; then
            TAG=$(date +'%Y%m%d')-${GITHUB_SHA::7}
          fi
          
          # Update deployment
          oc set image deployment/${{ github.event.repository.name }} \
            ${{ github.event.repository.name }}=ghcr.io/${{ steps.repo_name.outputs.name }}:${TAG}
          
          # Rollout and wait for deployment
          oc rollout status deployment/${{ github.event.repository.name }} --timeout=300s