name: Pull Request OWASP Analysis

on:
  pull_request:
    branches:
      - main
      - development
    types:
      - opened 
      - synchronize 
      - reopened 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Maven build and tests
        run: ./mvnw clean install

      - name: Run OWASP Dependency-Check (security scanning)
        run: ./mvnw dependency-check:check

      - name: Upload Dependency Check report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: target/dependency-check-report/
