name: 🧪 PR Validation

on:
  pull_request:
    branches: [ development, main ]
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-java

      - name: Set Repository Name
        id: repo_name
        run: |
          echo "name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]' | tr '/' '-')" >> $GITHUB_OUTPUT

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

  security:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: ./.github/actions/setup-java

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java  # Change to 'java' since Kotlin is analyzed as Java
          queries: security-extended,security-and-quality  # Add more comprehensive queries

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "pr-validation"
          upload: true
          wait-for-processing: true

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup-java

      - name: Run Tests
        run: ./mvnw test