name: 🧪 PR Validation

on:
  pull_request:
    branches: [ development, main ]
  workflow_dispatch:  # Manual trigger

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write  # This is crucial for CodeQL to upload results

    steps:
      - uses: actions/checkout@v3

      - name: Set Repository Name
        id: repo_name
        run: |
          echo "name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]' | tr '/' '-')" >> $GITHUB_OUTPUT
      
      - name: Code Linting
        run: |
          echo "TODO: Add linting steps (e.g., checkstyle, PMD, SpotBugs)"

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw
          
      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

        # Disable default CodeQL setup by skipping 'init' and use manual setup instead
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: kotlin
          # Optional: specify a custom query suite or additional queries
          queries: security-and-quality  # Only if you have custom queries

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: 'security'  # Specify the category for analysis
          output: 'codeql-results.sarif'
          
      - name: Testing
        run: |
          echo "TODO: Add tests"

      - name: Security Scans
        run: |
          echo "TODO: Add security scans (e.g., OWASP Dependency Check)"

      - name: Prepare Artifact Directory
        run: |
          mkdir -p build/quarkus-app/
          cp -r target/quarkus-app/* build/quarkus-app/

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.repo_name.outputs.name }}-build
          path: target/quarkus-app/
          retention-days: 1