name: Initialize New Repository
on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  setup-repository:
    runs-on: ubuntu-latest
    if: github.event.repository.created
    steps:
      - uses: actions/checkout@v4

      - name: Create empty main branch
        run: |
          git checkout --orphan main
          git rm -rf .
          git commit --allow-empty -m "Initial empty main branch"
          git push origin main

      - name: Create environments
        env:
          GH_TOKEN: ${{ secrets.REPO_INIT_TOKEN }}
        run: |
          # Create production environment
          gh api \
            --method PUT \
            /repos/${{ github.repository }}/environments/production

          # Create development environment
          gh api \
            --method PUT \
            /repos/${{ github.repository }}/environments/development

      - name: Set branch protection for main
        env:
          GH_TOKEN: ${{ secrets.REPO_INIT_TOKEN }}
        run: |
          gh api \
            --method PUT \
            /repos/${{ github.repository }}/branches/main/protection \
            -f required_status_checks[strict]=true \
            -f required_pull_request_reviews[required_approving_review_count]=2 \
            -f required_pull_request_reviews[dismiss_stale_reviews]=true \
            -f enforce_admins=true \
            -f required_linear_history=true \
            -f allow_force_pushes=false \
            -f allow_deletions=false

      - name: Set branch protection for development
        env:
          GH_TOKEN: ${{ secrets.REPO_INIT_TOKEN }}
        run: |
          gh api \
            --method PUT \
            /repos/${{ github.repository }}/branches/development/protection \
            -f required_status_checks[strict]=true \
            -f required_pull_request_reviews[required_approving_review_count]=2 \
            -f required_pull_request_reviews[dismiss_stale_reviews]=true \
            -f enforce_admins=false \
            -f required_linear_history=false \
            -f allow_force_pushes=false \
            -f allow_deletions=false